### ISSUE TITLE
Config variable ignored if value is blank (evaluates to null)

### ISSUE THREAD

**Issue by vmitchell85** [tightenco/jigsaw#109]
I have a `config.production.php` file and have purposefully set a variable to be an empty string `''`. When I run `jigsaw build production` it ignores the empty string and pulls the default that is in `config.php`.

I have confirmed that adding text into that variable in `config.production.php` does set the variable properly.

**Comment by damiani** [comment]
I just pushed a fix for that...update to v1.0.3 and test it out.

**Comment by vmitchell85** [comment]
Talk about a quick turn around... thanks, I'll check it out now.

**Comment by vmitchell85** [comment]
Still doesn't seem to be working.

Just to confirm my steps I did the following:
1. changed composer.json to use `dev-master`
2. Ran `composer update`
3. Ran `composer du`
4. Ran `jigsaw build` - local version is correct
5. Ran `jigsaw build production` - prod version is incorrect

config.php contents:
```php
<?php

return [
    'base_url' => 'http://example.com',
    'production' => false,
];
```
config.production.php contents:
```php
<?php

return [
    'base_url' => '',
    'production' => true,
    'build' => [
        'source' => "source",
        'destination' => "www"
    ]
];
```

**Comment by damiani** [comment]
Can you confirm your version by running `jigsaw -V`? And you're checking the results in the `build_production` directory?

Also, unrelated, but the key name in `config` for the base URL (if you want it added automatically to the `path`) should be the camel-cased `baseUrl`, not `base_url`.
